In [51]:
import pandas as pd

test_df = pd.read_csv('csv/test.csv')
test_df.head()

,video_id,vert_aperture,outer_vert_aperture,horiz_spread,inner_area,outer_area,compactness,lip_speed,rms_energy,digit_sequences,digit_sequences_filename,digit_segments
0,subset_01/subset_01/1100/1_1100_male_202503051...,"[0.03185812454443402, 0.031554723610500525, 0....","[0.23153276589535618, 0.2315409863243736, 0.23...","[0.5056430431499623, 0.5055021844399772, 0.504...","[0.002099045735230787, 0.0020735759286358464, ...","[0.032273314217493715, 0.032250364811546806, 0...","[0.09243672133082917, 0.0924164828918035, 0.09...","[0.0003345045633326953, 0.001829068852730524, ...","[0.0, 4.880944245453606e-08, 0.000506272773935...","[""3"", ""9"", ""2"", ""9"", ""4"", ""5"", ""6""]","[""3"", ""9"", ""2"", ""!"", ""9"", ""4"", ""5"", ""6""]","[[17, 22], [24, 28], [30, 33], [43, 47], [49, ..."
1,subset_01/subset_01/1100/1_1100_male_202503051...,"[0.0027415780032661353, 0.0030604360029516937,...","[0.19016776041700517, 0.19614128325990718, 0.1...","[0.5047538152501184, 0.5094151742361043, 0.503...","[0.0014309437120662476, 0.0004185877083775473,...","[0.024339077614003553, 0.02363941149387319, 0....","[0.07401929936992692, 0.0703208336959397, 0.07...","[0.0046722519217390806, 0.0009484920941092104,...","[0.0, 2.8483044606860164e-07, 0.00027679781300...","[""4"", ""0"", ""3"", ""5"", ""8"", ""2"", ""6"", ""7""]","[""4"", ""0"", ""3"", ""5"", ""8"", ""2"", ""6"", ""7""]","[[9, 14], [16, 20], [22, 27], [29, 33], [35, 3..."
2,subset_01/subset_01/1100/1_1100_male_202503051...,"[0.00247327940113811, 0.0029164257003514737, 0...","[0.18975085591514063, 0.18908158315211582, 0.1...","[0.5140874045002028, 0.5114424859710318, 0.514...","[0.0018689567718371413, 0.0020842069139014223,...","[0.026059388664452027, 0.0265390532635718, 0.0...","[0.07680300486801737, 0.0789514035858843, 0.07...","[0.002681785350929261, 0.0003581794381726733, ...","[0.0, 8.861525620073216e-08, 0.000239755954344...","[""1"", ""0"", ""9"", ""0"", ""5"", ""8"", ""7"", ""4""]","[""1"", ""0"", ""9"", ""0"", ""5"", ""8"", ""7"", ""4""]","[[8, 12], [14, 18], [20, 24], [26, 31], [33, 3..."
3,subset_01/subset_01/1100/1_1100_male_202503051...,"[0.002637016219305839, 0.002494582414746325, 0...","[0.1799974012774624, 0.18262600423555614, 0.18...","[0.521345405531607, 0.520605213155745, 0.52085...","[0.001832063287655573, 0.0011792735159713694, ...","[0.024250754490289843, 0.023973205313354604, 0...","[0.07077313840531911, 0.0698568074346365, 0.06...","[0.0007537719429412998, 0.00024383459424627912...","[0.0, 5.319303105751375e-07, 0.000318017692800...","[""8"", ""0"", ""8"", ""3"", ""5""]","[""!"", ""8"", ""!"", ""0"", ""8"", ""3"", ""5"", ""!""]","[[16, 20], [28, 38], [41, 45], [47, 51], [53, ..."
4,subset_01/subset_01/1100/1_1100_male_202503051...,"[0.007585522984637406, 0.006018191644007235, 0...","[0.19802346742750457, 0.2048591505958455, 0.21...","[0.4959935459947375, 0.5014194046968482, 0.504...","[0.0021086411003948483, 0.002253791293978983, ...","[0.02933221988613921, 0.029176484319988545, 0....","[0.09151928932911367, 0.08833260873743519, 0.0...","[0.005647696006921059, 0.004245609612736228, 0...","[0.0, 4.5124847654025085e-07, 0.00034994767316...","[""6"", ""8"", ""0"", ""2"", ""4"", ""6"", ""2"", ""3""]","[""6"", ""8"", ""0"", ""2"", ""4"", ""6"", ""2"", ""3""]","[[13, 16], [18, 22], [24, 29], [31, 35], [37, ..."

In [50]:
import json
df = pd.read_csv('csv/test.csv')
len(json.loads(df.loc[2, "vert_aperture"]))

65

In [53]:
test_df['vert_aperture'][0]

'[0.03185812454443402, 0.031554723610500525, 0.028304983838668113, 0.02428795340357536, 0.02339368199991249, 0.008158840824624668, 0.00759004574910437, 0.007196970458911387, 0.0075312637119312915, 0.007017920506105166, 0.010016622111518731, 0.010975578110106788, 0.007186731213970961, 0.012775012648153929, 0.005338672281495794, 0.005794431191547781, 0.006366394372242317, 0.009134509273500319, 0.010184650014885758, 0.014807267821238188, 0.014900564007216534, 0.021196887853838373, 0.020782392505104226, 0.019066923644731736, 0.01679997048555541, 0.01150822157220412, 0.019576861202855362, 0.04159552244978199, 0.03897569253174771, 0.031890541794714136, 0.027582605080010255, 0.03591936724006177, 0.03853038406464102, 0.03129665209951017, 0.02298258054321594, 0.01795904252709332, 0.01397121022960762, 0.006754793378414267, 0.006410921379619856, 0.00837386665185696, 0.010435733562623875, 0.010880425385528521, 0.005849450507700941, 0.005159819502611472, 0.0064883670593414615, 0.00523529078046912, 0.005152666347812739, 0.00605124519605905, 0.006418517909932515, 0.006893762172923189, 0.005232777969299873, 0.0051126184518519285, 0.004482260487197705, 0.0037374792349288747, 0.00486994092439215, 0.017745184282731554, 0.024568256160661342, 0.021234258249447847, 0.02070524898304101, 0.008685850497010771, 0.007684978530588839, 0.0051695642797722225, 0.005419168740512823]'

In [52]:
frame_df = pd.read_csv('csv/test_frames.csv')
frame_df.head()

,video_id,frame_idx,vert_aperture,outer_vert_aperture,horiz_spread,inner_area,outer_area,compactness,lip_speed,rms_energy
0,subset_01/subset_01/1100/1_1100_male_202503051...,0,0.031858,0.231533,0.505643,0.002099,0.032273,0.092437,0.000335,0.000000e+00
1,subset_01/subset_01/1100/1_1100_male_202503051...,1,0.031555,0.231541,0.505502,0.002074,0.032250,0.092416,0.001829,4.880944e-08
2,subset_01/subset_01/1100/1_1100_male_202503051...,2,0.028305,0.230462,0.504773,0.004095,0.033335,0.095747,0.005180,5.062728e-04
3,subset_01/subset_01/1100/1_1100_male_202503051...,3,0.024288,0.226518,0.512885,0.005300,0.035791,0.100542,0.006312,1.485352e-03
4,subset_01/subset_01/1100/1_1100_male_202503051...,4,0.023394,0.222937,0.516401,0.005148,0.035692,0.099665,0.008685,2.639090e-03

In [38]:
print(test_df['video_id'][0])
print(test_df['video_id'][1])

subset_01/subset_01/1100/1_1100_male_20250305175437_392!9456_Hinovaphone-Hera-BD00-Android11_train_1
subset_01/subset_01/1100/1_1100_male_20250305175440_40358267_Hinovaphone-Hera-BD00-Android11_train_2

In [44]:
test_df['digit_segments'][4]

'[[13, 16], [18, 22], [24, 29], [31, 35], [37, 41], [43, 46], [48, 51], [53, 67]]'

In [48]:
test_df['digit_sequences'][0]

'["3", "9", "2", "9", "4", "5", "6"]'

In [42]:
len(test_df['vert_aperture'][1])

1388

In [43]:
test_df['vert_aperture'][0]

'[0.03185812454443402, 0.031554723610500525, 0.028304983838668113, 0.02428795340357536, 0.02339368199991249, 0.008158840824624668, 0.00759004574910437, 0.007196970458911387, 0.0075312637119312915, 0.007017920506105166, 0.010016622111518731, 0.010975578110106788, 0.007186731213970961, 0.012775012648153929, 0.005338672281495794, 0.005794431191547781, 0.006366394372242317, 0.009134509273500319, 0.010184650014885758, 0.014807267821238188, 0.014900564007216534, 0.021196887853838373, 0.020782392505104226, 0.019066923644731736, 0.01679997048555541, 0.01150822157220412, 0.019576861202855362, 0.04159552244978199, 0.03897569253174771, 0.031890541794714136, 0.027582605080010255, 0.03591936724006177, 0.03853038406464102, 0.03129665209951017, 0.02298258054321594, 0.01795904252709332, 0.01397121022960762, 0.006754793378414267, 0.006410921379619856, 0.00837386665185696, 0.010435733562623875, 0.010880425385528521, 0.005849450507700941, 0.005159819502611472, 0.0064883670593414615, 0.00523529078046912, 0.005152666347812739, 0.00605124519605905, 0.006418517909932515, 0.006893762172923189, 0.005232777969299873, 0.0051126184518519285, 0.004482260487197705, 0.0037374792349288747, 0.00486994092439215, 0.017745184282731554, 0.024568256160661342, 0.021234258249447847, 0.02070524898304101, 0.008685850497010771, 0.007684978530588839, 0.0051695642797722225, 0.005419168740512823]'

In [29]:
df = pd.read_csv('csv/train.csv')
row = df.iloc[0]
vert_ap = row['vert_aperture']
len(vert_ap)

1525

In [1]:
import torch
torch.cuda.is_available()

True

In [1]:
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

In [ ]:
model_path = "data/face_landmarker.task"


BaseOptions = mp.tasks.BaseOptions
FaceLandmarker = mp.tasks.vision.FaceLandmarker
FaceLandmarkerOptions = mp.tasks.vision.FaceLandmarkerOptions
VisionRunningMode = mp.tasks.vision.RunningMode

options = FaceLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.IMAGE)

with FaceLandmarker.create_from_options(options) as landmarker:
  # The landmarker is initialized. Use it here.
  # ...
    pass

## VIsualization Utils

In [3]:
%matplotlib inline

In [ ]:
#@markdown We implemented some functions to visualize the face landmark detection results. <br/> Run the following cell to activate the functions.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from mediapipe.tasks.python.vision import drawing_utils
from mediapipe.tasks.python.vision import drawing_styles
import numpy as np
import matplotlib.pyplot as plt


def draw_landmarks_on_image(rgb_image, detection_result):
  face_landmarks_list = detection_result.face_landmarks
  annotated_image = np.copy(rgb_image)

  # Loop through the detected faces to visualize.
  for idx in range(len(face_landmarks_list)):
    face_landmarks = face_landmarks_list[idx]

    # Draw the face landmarks.


    # drawing_utils.draw_landmarks(
    #     image=annotated_image,
    #     landmark_list=face_landmarks,
    #     connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_TESSELATION,
    #     landmark_drawing_spec=None,
    #     connection_drawing_spec=drawing_styles.get_default_face_mesh_tesselation_style())
    drawing_utils.draw_landmarks(
        image=annotated_image,
        landmark_list=face_landmarks,
        connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_CONTOURS,
        landmark_drawing_spec=None,
        connection_drawing_spec=drawing_styles.get_default_face_mesh_contours_style())
   
    # drawing_utils.draw_landmarks(
    #     image=annotated_image,
    #     landmark_list=face_landmarks,
    #     connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_LEFT_IRIS,
    #       landmark_drawing_spec=None,
    #       connection_drawing_spec=drawing_styles.get_default_face_mesh_iris_connections_style())
    # drawing_utils.draw_landmarks(
    #     image=annotated_image,
    #     landmark_list=face_landmarks,
    #     connections=vision.FaceLandmarksConnections.FACE_LANDMARKS_RIGHT_IRIS,
    #       landmark_drawing_spec=None,
    #       connection_drawing_spec=drawing_styles.get_default_face_mesh_iris_connections_style())

  return annotated_image

def plot_face_blendshapes_bar_graph(face_blendshapes):
  # Extract the face blendshapes category names and scores.
  face_blendshapes_names = [face_blendshapes_category.category_name for face_blendshapes_category in face_blendshapes]
  face_blendshapes_scores = [face_blendshapes_category.score for face_blendshapes_category in face_blendshapes]
  print("Face Blendshapes category names: ", face_blendshapes_names)
  print("Face Blendshapes category scores: ", face_blendshapes_scores)
  # The blendshapes are ordered in decreasing score value.
  face_blendshapes_ranks = range(len(face_blendshapes_names))

  fig, ax = plt.subplots(figsize=(12, 12))
  bar = ax.barh(face_blendshapes_ranks, face_blendshapes_scores, label=[str(x) for x in face_blendshapes_ranks])
  ax.set_yticks(face_blendshapes_ranks, face_blendshapes_names)
  ax.invert_yaxis()

  # Label each bar with values
  for score, patch in zip(face_blendshapes_scores, bar.patches):
    plt.text(patch.get_x() + patch.get_width(), patch.get_y(), f"{score:.4f}", va="top")

  ax.set_xlabel('Score')
  ax.set_title("Face Blendshapes")
  plt.tight_layout()
  plt.show()

In [ ]:
# STEP 2: Create an FaceLandmarker object.
import cv2
model_path = "face_landmarker.task"
base_options = python.BaseOptions(model_asset_path=model_path)
options = vision.FaceLandmarkerOptions(base_options=base_options,
                                       output_face_blendshapes=True,
                                       output_facial_transformation_matrixes=True,
                                       num_faces=1)
detector = vision.FaceLandmarker.create_from_options(options)

# STEP 3: Load the input image.
image = mp.Image.create_from_file("face1.png")

# STEP 4: Detect face landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
plt.imshow(annotated_image)

In [ ]:
# STEP 3: Load the input image.
image = mp.Image.create_from_file("face2.png")

# STEP 4: Detect face landmarks from the input image.
detection_result = detector.detect(image)

# STEP 5: Process the detection result. In this case, visualize it.
annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)
plt.imshow(annotated_image)

In [2]:
from model import SequenceVerifier, DigitVerifier
model = SequenceVerifier()
model

SequenceVerifier(
  (lip_encoder): LipEncoder(
    (conv): Sequential(
      (0): Conv1d(5, 32, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Conv1d(32, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
    )
    (gru): GRU(64, 128, batch_first=True, bidirectional=True)
    (fc): Linear(in_features=256, out_features=64, bias=True)
  )
  (digit_embedding): Embedding(11, 64)
  (digit_compare): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=64, out_features=1, bias=True)
  )
  (seq_agg): Sequential(
    (0): Linear(in_features=8, out_features=32, bias=True)
    (1): ReLU()
    (2): Linear(in_features=32, out_features=1, bias=True)
  )
)

In [4]:
model = DigitVerifier()
model

DigitVerifier(
  (lip_encoder): LipEncoder(
    (conv): Sequential(
      (0): Conv1d(5, 32, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): ReLU()
      (3): Conv1d(32, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): ReLU()
    )
    (gru): GRU(64, 128, batch_first=True, bidirectional=True)
    (fc): Linear(in_features=256, out_features=64, bias=True)
  )
  (digit_embedding): Embedding(11, 64)
  (classifier): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=64, out_features=1, bias=True)
  )
)